server:
  port: 8200

spring:
  application:
    name: Emp-Service
  #consul的配置
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        #注册到consul的服务名
        service-name: Emp-consul
management:
  endpoints:
    web:
      exposure:
        include: "*"



#监控的微服务配置
#启用熔断器
feign:
  hystrix:
    enabled: true
#如果启动报错，找不到hystrix.stream，在你要监控的微服务加入如下配置。:
management:
  endpoints:
    web:
      exposure:
        include: "*"
